/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.APIController;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Chiquang
 */
public class ItemFilm extends javax.swing.JPanel {

    protected String id = "null";
    protected String path = "null";
    protected String title = "null";
    protected String description = "null";
    
    public ItemFilm(String id, String path, String title, String description) {
        this.id = id;
        this.path = path;
        this.title = title;
        this.description = description;
        initComponents();        
        try {
            titleTxt.setText(title);
            descriptionTxt.setText(title);
            String newPath = null;            
            if(!path.equals("null")) {
                newPath = APIController.imageURL + path;
                URL url = new URL(newPath);
                Image image = ImageIO.read(url);
                image = image.getScaledInstance(150,210,Image.SCALE_DEFAULT);
                image_handled.setIcon(new ImageIcon(image));
            }
            else {
                newPath = ".\\src\\assets\\icon\\noimage.jpg";
                Image image = ImageIO.read(new File(newPath));
                image = image.getScaledInstance(150,210,Image.SCALE_DEFAULT);
                image_handled.setIcon(new ImageIcon(image));
            }
        } catch (IOException e) {
            System.out.println("Error: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image_handled = new javax.swing.JLabel();
        titleTxt = new javax.swing.JLabel();
        descriptionTxt = new javax.swing.JLabel();
        viewBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        titleTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleTxt.setForeground(new java.awt.Color(255, 255, 255));
        titleTxt.setText("Title");

        descriptionTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        descriptionTxt.setForeground(new java.awt.Color(255, 255, 255));
        descriptionTxt.setText("Decription");

        viewBtn.setBackground(new java.awt.Color(255, 255, 255));
        viewBtn.setForeground(new java.awt.Color(0, 153, 255));
        viewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/eye.png"))); // NOI18N
        viewBtn.setText("Xem chi tiết");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(image_handled, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleTxt)
                            .addComponent(descriptionTxt))
                        .addContainerGap(168, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewBtn)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewBtn)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(image_handled, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        String message = id + ";search;null;detail-null";
        Home_GUI.client.writeMessageToServer(message);
        Home_GUI.client.readMessageFromServer();
        new FilmDetail_GUI().run();
    }//GEN-LAST:event_viewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionTxt;
    private javax.swing.JLabel image_handled;
    private javax.swing.JLabel titleTxt;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
