/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.HandleImageController;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Chiquang
 */
public class ResizeImage_GUI extends javax.swing.JFrame {
    public HandleImageController handleImageController = new HandleImageController();
    /**
     * Creates new form ResizeImage_GUI
     */
    public ResizeImage_GUI() {
        initComponents();
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        smallBtn = new javax.swing.JButton();
        mediumBtn = new javax.swing.JButton();
        largeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(800, 250));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Choose file extension type");

        smallBtn.setBackground(new java.awt.Color(51, 51, 255));
        smallBtn.setForeground(new java.awt.Color(255, 255, 255));
        smallBtn.setText("Small");
        smallBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallBtnActionPerformed(evt);
            }
        });

        mediumBtn.setBackground(new java.awt.Color(51, 51, 255));
        mediumBtn.setForeground(new java.awt.Color(255, 255, 255));
        mediumBtn.setText("Medium");
        mediumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumBtnActionPerformed(evt);
            }
        });

        largeBtn.setBackground(new java.awt.Color(51, 51, 255));
        largeBtn.setForeground(new java.awt.Color(255, 255, 255));
        largeBtn.setText("Large");
        largeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(255, 0, 0));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Thoát");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(smallBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mediumBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(largeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smallBtn)
                    .addComponent(mediumBtn)
                    .addComponent(largeBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smallBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallBtnActionPerformed
        String encode = handleImageController.convertFileToString(HandleImage_GUI.path);
        String extension = handleImageController.getExtensionFile(HandleImage_GUI.path);
        String message = encode + ";zoom;" + extension + ";small";
        Home_GUI.client.writeMessageToServer(message);
        Home_GUI.client.readMessageFromServer();
        ImageIcon imageIcon = new ImageIcon(Home_GUI.client.message_from_server);        
        JOptionPane.showMessageDialog(this, "", "Image result", JOptionPane.YES_OPTION, imageIcon);
        this.dispose();
    }//GEN-LAST:event_smallBtnActionPerformed

    private void mediumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumBtnActionPerformed
        String encode = handleImageController.convertFileToString(HandleImage_GUI.path);
        String extension = handleImageController.getExtensionFile(HandleImage_GUI.path);
        String message = encode + ";zoom;" + extension + ";medium";
        Home_GUI.client.writeMessageToServer(message);
        Home_GUI.client.readMessageFromServer();
        ImageIcon imageIcon = new ImageIcon(Home_GUI.client.message_from_server);        
        JOptionPane.showMessageDialog(this, "", "Image result", JOptionPane.YES_OPTION, imageIcon);
        this.dispose();
    }//GEN-LAST:event_mediumBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();       
    }//GEN-LAST:event_backBtnActionPerformed

    private void largeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeBtnActionPerformed
        String encode = handleImageController.convertFileToString(HandleImage_GUI.path);
        String extension = handleImageController.getExtensionFile(HandleImage_GUI.path);
        String message = encode + ";zoom;" + extension + ";large";
        Home_GUI.client.writeMessageToServer(message);
        Home_GUI.client.readMessageFromServer();
        ImageIcon imageIcon = new ImageIcon(Home_GUI.client.message_from_server);        
        JOptionPane.showMessageDialog(this, "", "Image result", JOptionPane.YES_OPTION, imageIcon);
        this.dispose();
    }//GEN-LAST:event_largeBtnActionPerformed
    
    public void run() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResizeImage_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton largeBtn;
    private javax.swing.JButton mediumBtn;
    private javax.swing.JButton smallBtn;
    // End of variables declaration//GEN-END:variables
}
